### ISSUE TITLE
Refine search results

### ISSUE THREAD

**Issue by neilpie** [pie/Pannells-Child-Theme#11]
When you use the search
function, we would like it to
exclude searching posts or
things from the Homepage.
We searched for ‘Lorem’ and
it pulled in this ‘home header’
item, which we dont want to
come up in results. 
<img width="392" alt="screenshot 2016-09-21 22 34 48" src="https://cloud.githubusercontent.com/assets/488297/18729896/9ec0a09c-804b-11e6-8974-84105c3bef80.png">

**Comment by neilpie** [comment]
Specifically, which content would you like indexed? Just posts? Also pages? Any other post types?

**Comment by dynamicpear** [comment]
Hi Neil. We would just like all of the 'pages' to appear in the search result index. None of the posts.

**Comment by neilpie** [comment]
This can be achieved quite simply by installing https://wordpress.org/plugins/relevanssi/
