### ISSUE TITLE
Bullet point text is larger than body text.

### ISSUE THREAD

**Issue by dynamicpear** [pie/Pannells-Child-Theme#17]
Bullet point text is larger than body text. Please make the same size.

See as example:
http://pannells.staging.wpengine.com/what-our-clients-say/

**Comment by neilpie** [comment]
add p, ul, ol to font-size declaration for the <p> element @pie/developers

**Comment by dynamicpear** [comment]
Hi Neil. Now the bullets points are the correct size, but the side menu links, main menu and footer text have all reduced in size. Can they revert back to their previous size please.
